version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/static  # Монтируем статические файлы в общий том
    env_file: ".env.server"
    depends_on:
      - db
      - redis
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - static_volume:/app/static  # Монтируем общий том с статическими файлами
    depends_on:
      - web
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:
  static_volume:  # Общий том для статических файлов

networks:
  app-network:
    driver: bridge