version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"  # Внутренний порт для Django
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - ALLOWED_HOSTS=natalis-domini.ru,localhost,192.144.12.96
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
  environment:
    POSTGRES_DB: artgallery
    POSTGRES_USER: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    build: .
    command: celery -A config worker -l INFO
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - web

volumes:
  postgres_data:
  redis_data: