# Generated by Django 5.1.5 on 2025-02-18 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='введите жанр', max_length=100, null=True, verbose_name='жанр')),
            ],
            options={
                'verbose_name': 'жанр',
                'verbose_name_plural': 'жанры',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('text', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='серия, например, птица или обезьянки и т.д.', max_length=100, null=True, verbose_name='серия')),
            ],
            options={
                'verbose_name': 'серия',
                'verbose_name_plural': 'серии',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_number', models.PositiveIntegerField(blank=True, help_text='номер формируется автоматически', null=True, verbose_name='порядковый номер серии')),
                ('name', models.CharField(blank=True, help_text='серия плюс номер', max_length=100, null=True, verbose_name='название')),
                ('size', models.CharField(choices=[('_40x60', '40x60 см'), ('_30x40', '30x40 см'), ('_50x60', '50x60 см'), ('_20x20', '20x20 см')], help_text='выберите размер', max_length=100, verbose_name='размер')),
                ('material', models.CharField(choices=[('thick_cardboard', 'плотный картон, хлопок'), ('fiberboard_canvas', 'холст на ДВП, хлопок'), ('canvas_on_a_stretcher', 'холст на подрамнике')], help_text='выберите материал', max_length=100, verbose_name='материал')),
                ('paint_property', models.CharField(choices=[('oil', 'масляные'), ('acrylic', 'акриловые'), ('tempera', 'темпера')], help_text='выберите свойство краски', max_length=100, verbose_name='краска')),
                ('picture', models.ImageField(help_text='загрузите картину', upload_to='gallery/', verbose_name='путь к картине')),
                ('description', models.TextField(blank=True, help_text='опишите картину', null=True, verbose_name='описание')),
                ('genre', models.ForeignKey(help_text='внешний ключ на жанр', on_delete=django.db.models.deletion.DO_NOTHING, to='gallery.genre', verbose_name='жанр')),
                ('series', models.ForeignKey(help_text='внешний ключ на стиль', on_delete=django.db.models.deletion.DO_NOTHING, to='gallery.series', verbose_name='серия')),
            ],
            options={
                'verbose_name': 'картина',
                'verbose_name_plural': 'картины',
                'ordering': ['pk'],
            },
        ),
    ]
