# Generated by Django 5.1.5 on 2025-11-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='detailed_description',
            field=models.TextField(blank=True, help_text='создайте описание картины', null=True, verbose_name='подробное описание'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='size',
            field=models.CharField(choices=[('_40x60', '40x60 см'), ('_30x40', '30x40 см'), ('_50x60', '50x60 см'), ('_20x20', '20x20 см'), ('_70x20', '70x20 см'), ('_60x80', '60x80 см'), ('_40x50', '40x50 см'), ('_50x70', '50x70 см'), ('_50x50', '50x50 см')], help_text='выберите размер', max_length=100, verbose_name='размер'),
        ),
    ]
